Repository Azure/azure-dev, pull requests merged in 2023-03, with the labels that each got.

#1650 Support lower-cased bicep types
  cli/azd/.vscode/cspell-azd-dictionary.txt
  cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
  cli/azd/test/functional/testdata/samples/storage/infra/main.bicep
Labels: blocker

#1629 Add AKS service target
  .vscode/cspell.global.yaml
  .vscode/launch.json
  cli/azd/cmd/container.go
  cli/azd/pkg/account/manager_test.go
  cli/azd/pkg/azure/resource_ids.go
  cli/azd/pkg/environment/environment.go
  cli/azd/pkg/exec/command_runner.go
  cli/azd/pkg/exec/runargs.go
  cli/azd/pkg/infra/azure_resource_types.go
  cli/azd/pkg/project/framework_service_docker.go
  cli/azd/pkg/project/framework_service_docker_test.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_target.go
  cli/azd/pkg/project/service_target_aks.go
  cli/azd/pkg/project/service_target_aks_test.go
  cli/azd/pkg/project/service_target_containerapp.go
  cli/azd/pkg/project/service_target_containerapp_test.go
  cli/azd/pkg/tools/azcli/azcli.go
  cli/azd/pkg/tools/azcli/container_registry.go
  cli/azd/pkg/tools/azcli/managed_clusters.go
  cli/azd/pkg/tools/docker/docker.go
  cli/azd/pkg/tools/kubectl/kube_config.go
  cli/azd/pkg/tools/kubectl/kube_config_test.go
  cli/azd/pkg/tools/kubectl/kubectl.go
  cli/azd/pkg/tools/kubectl/kubectl_test.go
  cli/azd/pkg/tools/kubectl/models.go
  cli/azd/pkg/tools/kubectl/util.go
  cli/azd/resources/templates.json
  cli/azd/test/mocks/mock_context.go
  eng/pipelines/release-cli.yml
  eng/pipelines/templates/steps/install-kubectl.yml
  go.mod
  go.sum
  schemas/v1.0/azure.yaml.json
Labels: host, aks

#1665 Adding check to ensure the selected adapter is "up"
  cli/azd/internal/telemetry/resource/machine_id.go
Labels: blocker

#1667 Adds support to reload environment values
  cli/azd/cmd/middleware/hooks.go
  cli/azd/pkg/config/manager.go
  cli/azd/pkg/environment/environment.go
  cli/azd/pkg/environment/environment_test.go
  cli/azd/pkg/ext/hooks_runner.go
  cli/azd/pkg/ext/hooks_runner_test.go
  cli/azd/pkg/project/service_target_aks.go
Labels: bug, blocker

#1672 Notice manual update
  NOTICE.txt
Labels: blocker

#1630 Adds AKS todo template
  eng/pipelines/repoman.yml
  eng/pipelines/templates/steps/template-test-run-job.yml
  templates/common/.devcontainer/devcontainer.json/aks/nodejs/devcontainer.json
  templates/common/infra/bicep/core/gateway/apim.bicep
  templates/common/infra/bicep/core/host/aks-agent-pool.bicep
  templates/common/infra/bicep/core/host/aks-managed-cluster.bicep
  templates/common/infra/bicep/core/host/aks.bicep
  templates/common/infra/bicep/core/host/container-registry.bicep
  templates/common/infra/bicep/core/security/registry-access.bicep
  templates/cspell-templates.txt
  templates/todo/projects/nodejs-mongo-aks/.repo/bicep/azure.yaml
  templates/todo/projects/nodejs-mongo-aks/.repo/bicep/infra/main.bicep
  templates/todo/projects/nodejs-mongo-aks/.repo/bicep/infra/main.parameters.json
  templates/todo/projects/nodejs-mongo-aks/.repo/bicep/repo.yaml
  templates/todo/projects/nodejs-mongo-aks/.vscode/launch.json
  templates/todo/projects/nodejs-mongo-aks/.vscode/tasks.json
  templates/todo/projects/nodejs-mongo-aks/README.md
  templates/todo/projects/nodejs-mongo-aks/assets/resources.png
  templates/todo/projects/nodejs-mongo-aks/src/api/manifests/deployment.yaml
  templates/todo/projects/nodejs-mongo-aks/src/api/manifests/ingress.yaml
  templates/todo/projects/nodejs-mongo-aks/src/api/manifests/service.yaml
  templates/todo/projects/nodejs-mongo-aks/src/web/manifests/deployment.yaml
  templates/todo/projects/nodejs-mongo-aks/src/web/manifests/ingress.yaml
  templates/todo/projects/nodejs-mongo-aks/src/web/manifests/service.yaml
Labels: blocker, templates, aks

#1692 Installs kubectl to the Azd image used in CI
  cli/Dockerfile
Labels: blocker, aks

#1717 Feat: Update terraform provider versions
  cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/provider.tf
  cli/azd/test/functional/testdata/samples/resourcegroupterraformremote/infra/provider.tf
  templates/common/infra/terraform/core/database/cosmos/cosmos.tf
  templates/common/infra/terraform/core/gateway/apim-api/apim-api.tf
  templates/common/infra/terraform/core/gateway/apim/apim.tf
  templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode.tf
  templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython.tf
  templates/common/infra/terraform/core/host/appserviceplan/appserviceplan.tf
  templates/common/infra/terraform/core/monitor/applicationinsights/applicationinsights.tf
  templates/common/infra/terraform/core/monitor/loganalytics/loganalytics.tf
  templates/common/infra/terraform/core/security/keyvault/keyvault.tf
  templates/todo/projects/nodejs-mongo/.repo/terraform/infra/provider.tf
  templates/todo/projects/python-mongo/.repo/terraform/infra/provider.tf
Labels: customer-reported

#1711 Project/Service refactor to support new `build` command
  cli/azd/.vscode/cspell-azd-dictionary.txt
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/env.go
  cli/azd/cmd/infra_create.go
  cli/azd/cmd/middleware/hooks_test.go
  cli/azd/cmd/restore.go
  cli/azd/cmd/show.go
  cli/azd/cmd/util.go
  cli/azd/internal/repository/initializer.go
  cli/azd/internal/repository/initializer_test.go
  cli/azd/pkg/commands/pipeline/pipeline.go
  cli/azd/pkg/commands/pipeline/pipeline_manager.go
  cli/azd/pkg/commands/pipeline/pipeline_test.go
  cli/azd/pkg/ioc/service_locator.go
  cli/azd/pkg/project/framework_service.go
  cli/azd/pkg/project/framework_service_docker.go
  cli/azd/pkg/project/framework_service_docker_test.go
  cli/azd/pkg/project/framework_service_dotnet.go
  cli/azd/pkg/project/framework_service_dotnet_test.go
  cli/azd/pkg/project/framework_service_maven.go
  cli/azd/pkg/project/framework_service_npm.go
  cli/azd/pkg/project/framework_service_python.go
  cli/azd/pkg/project/project.go
  cli/azd/pkg/project/project_config.go
  cli/azd/pkg/project/project_config_test.go
  cli/azd/pkg/project/project_manager.go
  cli/azd/pkg/project/project_test.go
  cli/azd/pkg/project/resource_manager.go
  cli/azd/pkg/project/service.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_config_test.go
  cli/azd/pkg/project/service_manager.go
  cli/azd/pkg/project/service_target.go
  cli/azd/pkg/project/service_target_aks.go
  cli/azd/pkg/project/service_target_aks_test.go
  cli/azd/pkg/project/service_target_appservice.go
  cli/azd/pkg/project/service_target_appservice_test.go
  cli/azd/pkg/project/service_target_containerapp.go
  cli/azd/pkg/project/service_target_containerapp_test.go
  cli/azd/pkg/project/service_target_functionapp.go
  cli/azd/pkg/project/service_target_functionapp_test.go
  cli/azd/pkg/project/service_target_staticwebapp.go
  cli/azd/pkg/project/service_target_staticwebapp_test.go
  cli/azd/pkg/project/service_test.go
  cli/azd/pkg/tools/dotnet/dotnet.go
  cli/azd/pkg/tools/maven/maven.go
  cli/azd/test/functional/cli_test.go
Labels: cli, design, code improvements

#1614 Add CDN infra
  templates/common/infra/bicep/core/networking/cdn-endpoint.bicep
  templates/common/infra/bicep/core/networking/cdn-profile.bicep
  templates/common/infra/bicep/core/networking/cdn.bicep
Labels: blocker

#1794 Fix maven tool dependencies
  cli/azd/cmd/deploy.go
  cli/azd/cmd/env.go
Labels: cli, java

#1771 Template updates to support build/package changes
  templates/todo/web/react-fluent/Dockerfile
  templates/todo/web/react-fluent/package.json
Labels: templates

#1496 Enhancement of Terraform modules for App Service - Enable free plan
  templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode.tf
  templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode_variables.tf
  templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython.tf
  templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython_variables.tf
Labels: customer-reported

#1775 Reorder azd commands / new package command
  cli/azd/cmd/build.go
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/middleware/middleware.go
  cli/azd/cmd/package.go
  cli/azd/cmd/restore.go
  cli/azd/cmd/root.go
  cli/azd/cmd/testdata/TestUsage-azd.snap
  cli/azd/cmd/util.go
  cli/azd/pkg/input/console.go
  cli/azd/pkg/output/ux/endpoint.go
  cli/azd/pkg/project/container_helper.go
  cli/azd/pkg/project/container_helper_test.go
  cli/azd/pkg/project/framework_service.go
  cli/azd/pkg/project/framework_service_docker.go
  cli/azd/pkg/project/framework_service_docker_test.go
  cli/azd/pkg/project/framework_service_dotnet.go
  cli/azd/pkg/project/framework_service_maven.go
  cli/azd/pkg/project/framework_service_npm.go
  cli/azd/pkg/project/framework_service_python.go
  cli/azd/pkg/project/project_manager.go
  cli/azd/pkg/project/project_utils.go
  cli/azd/pkg/project/service_manager.go
  cli/azd/pkg/project/service_manager_test.go
  cli/azd/pkg/project/service_models.go
  cli/azd/pkg/project/service_target.go
  cli/azd/pkg/project/service_target_aks.go
  cli/azd/pkg/project/service_target_aks_test.go
  cli/azd/pkg/project/service_target_appservice.go
  cli/azd/pkg/project/service_target_containerapp.go
  cli/azd/pkg/project/service_target_functionapp.go
  cli/azd/pkg/project/service_target_staticwebapp.go
  cli/azd/pkg/tools/docker/docker.go
  cli/azd/pkg/tools/docker/docker_test.go
Labels: cli, command
