Repository Azure/azure-dev, pull requests merged in 2023-01, with the labels that each got.

#1316 Fix AzureDeveloperCredential for Java
  templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/AzureDeveloperCliCredential.java
Labels: blocker

#1253 Extensibility: Adds middleware pipeline to AZD actions (IoC)
  .vscode/cspell.global.yaml
  cli/azd/cmd/actions/action_descriptor.go
  cli/azd/cmd/actions_test.go
  cli/azd/cmd/auth.go
  cli/azd/cmd/auth_token.go
  cli/azd/cmd/auth_token_test.go
  cli/azd/cmd/cobra_builder.go
  cli/azd/cmd/config.go
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/down.go
  cli/azd/cmd/env.go
  cli/azd/cmd/infra.go
  cli/azd/cmd/infra_create.go
  cli/azd/cmd/infra_delete.go
  cli/azd/cmd/init.go
  cli/azd/cmd/login.go
  cli/azd/cmd/logout.go
  cli/azd/cmd/middleware/debug.go
  cli/azd/cmd/middleware/middleware.go
  cli/azd/cmd/middleware/middleware_test.go
  cli/azd/cmd/middleware/telemetry.go
  cli/azd/cmd/middleware/telemetry_test.go
  cli/azd/cmd/monitor.go
  cli/azd/cmd/pipeline.go
  cli/azd/cmd/pipeline_test.go
  cli/azd/cmd/provision.go
  cli/azd/cmd/restore.go
  cli/azd/cmd/root.go
  cli/azd/cmd/sets.go
  cli/azd/cmd/show.go
  cli/azd/cmd/telemetry.go
  cli/azd/cmd/templates.go
  cli/azd/cmd/templates_test.go
  cli/azd/cmd/up.go
  cli/azd/cmd/usage_test.go
  cli/azd/cmd/version.go
  cli/azd/cmd/wire.go
  cli/azd/cmd/wire_gen.go
  cli/azd/docs/docgen.go
  cli/azd/internal/repository/initializer.go
  cli/azd/internal/repository/initializer_test.go
  cli/azd/main.go
  cli/azd/pkg/ioc/container.go
  cli/azd/pkg/output/parameter.go
  cli/azd/test/functional/up_test.go
  go.mod
  go.sum
Labels: blocker, cli, extensibility

#1320 Display APIM and Cache-Redis created resource
  cli/azd/pkg/infra/azure_resource_types.go
Labels: blocker

#1312 Allow configuration of service endpoint using `SERVICE_<service>_ENDPOINTS`
  cli/azd/pkg/environment/environment.go
  cli/azd/pkg/infra/provisioning/provisioning.go
  cli/azd/pkg/project/service.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_target_containerapp.go
  cli/azd/pkg/project/service_test.go
  cli/azd/test/functional/cli_test.go
  cli/azd/test/functional/testdata/expected-output-types/typed-values.env
  cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/output.tf
  cli/azd/test/functional/testdata/samples/storage/infra/main.bicep
  templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
Labels: blocker

#1325 Checks for container registration errors vs actual errors
  cli/azd/cmd/cobra_builder.go
  cli/azd/pkg/ioc/container.go
  cli/azd/pkg/ioc/container_test.go
Labels: blocker, cli

#1332 Fix cors param in task for python func template
  templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
Labels: blocker

#1311 Install script uses MSI on Windows
  cli/installer/install-azd.ps1
  cli/installer/test-win-install.ps1
  eng/pipelines/release-cli.yml
Labels: blocker

#1331 Add notices to Windows Installer package
  cli/installer/windows/azd.wxs
  cli/installer/windows/notices.rtf
  cli/installer/windows/ui.wxs
Labels: blocker, installer

#1349 Bump loader-utils & Todo Web App package-lock.json
  templates/todo/web/react-fluent/package-lock.json
Labels: dependencies

#1236 Extensibility: Command Hooks lib components
  .vscode/cspell.global.yaml
  cli/azd/pkg/environment/environment.go
  cli/azd/pkg/ext/hooks_manager.go
  cli/azd/pkg/ext/hooks_manager_test.go
  cli/azd/pkg/ext/hooks_runner.go
  cli/azd/pkg/ext/hooks_runner_test.go
  cli/azd/pkg/ext/models.go
  cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
  cli/azd/pkg/project/framework_service_npm.go
  cli/azd/pkg/tools/bash/bash.go
  cli/azd/pkg/tools/bash/bash_test.go
  cli/azd/pkg/tools/powershell/powershell.go
  cli/azd/pkg/tools/powershell/powershell_test.go
  cli/azd/pkg/tools/script.go
Labels: cli, extensibility

#1429 Extensibility: Azd Hooks middleware
  .vscode/launch.json
  cli/azd/cmd/actions/action_descriptor_test.go
  cli/azd/cmd/cobra_builder.go
  cli/azd/cmd/cobra_builder_test.go
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/env.go
  cli/azd/cmd/infra.go
  cli/azd/cmd/infra_create.go
  cli/azd/cmd/infra_delete.go
  cli/azd/cmd/middleware/hooks.go
  cli/azd/cmd/middleware/hooks_test.go
  cli/azd/cmd/restore.go
  cli/azd/cmd/root.go
  cli/azd/cmd/util.go
  cli/azd/pkg/ext/event_dispatcher.go
  cli/azd/pkg/ext/event_dispatcher_test.go
  cli/azd/pkg/ext/hooks_runner.go
  cli/azd/pkg/ext/hooks_runner_test.go
  cli/azd/pkg/project/framework_service_dotnet.go
  cli/azd/pkg/project/project_config.go
  cli/azd/pkg/project/project_config_test.go
  cli/azd/pkg/project/service.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_config_test.go
  schemas/v1.0/azure.yaml.json
Labels: cli, extensibility
