Repository Azure/azure-dev, pull requests merged in 2023-02, with the labels that each got.

#1480 Azd Hook bug fixes
  cli/azd/cmd/down.go
  cli/azd/cmd/middleware/hooks.go
  cli/azd/cmd/middleware/hooks_test.go
  cli/azd/cmd/provision.go
  cli/azd/cmd/up.go
  cli/azd/pkg/ext/hooks_runner.go
  cli/azd/pkg/ext/models.go
Labels: blocker

#1486 Fixes service event hooks firing correctly in azd up
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/env.go
  cli/azd/cmd/infra_create.go
  cli/azd/cmd/infra_delete.go
  cli/azd/cmd/middleware/hooks.go
  cli/azd/cmd/middleware/hooks_test.go
  cli/azd/cmd/restore.go
  cli/azd/pkg/ext/models.go
  cli/azd/pkg/project/project_config.go
Labels: blocker

#1407 ux pipeline config
  cli/azd/cmd/pipeline.go
  cli/azd/internal/repository/initializer.go
  cli/azd/pkg/azdo/service_connection.go
  cli/azd/pkg/azdo/utils.go
  cli/azd/pkg/commands/pipeline/azdo_provider.go
  cli/azd/pkg/commands/pipeline/azdo_provider_test.go
  cli/azd/pkg/commands/pipeline/github_provider.go
  cli/azd/pkg/commands/pipeline/github_provider_test.go
  cli/azd/pkg/commands/pipeline/pipeline.go
  cli/azd/pkg/commands/pipeline/pipeline_manager.go
  cli/azd/pkg/contracts/envelope.go
  cli/azd/pkg/input/console.go
  cli/azd/pkg/output/ux/created_repo_secret.go
  cli/azd/pkg/output/ux/warning.go
  cli/azd/pkg/tools/git/git.go
Labels: blocker

#1478 Multitenancy support
  cli/azd/cmd/container.go
  cli/azd/cmd/deploy.go
  cli/azd/cmd/env.go
  cli/azd/cmd/infra_create.go
  cli/azd/cmd/infra_delete.go
  cli/azd/cmd/init.go
  cli/azd/cmd/login.go
  cli/azd/cmd/logout.go
  cli/azd/cmd/middleware/ensure_login.go
  cli/azd/cmd/monitor.go
  cli/azd/cmd/pipeline.go
  cli/azd/cmd/restore.go
  cli/azd/cmd/root.go
  cli/azd/cmd/show.go
  cli/azd/cmd/testdata/TestUsage-azd-login.snap
  cli/azd/cmd/util.go
  cli/azd/cmd/util_test.go
  cli/azd/pkg/account/manager.go
  cli/azd/pkg/account/manager_test.go
  cli/azd/pkg/account/models.go
  cli/azd/pkg/account/subscriptions_cache.go
  cli/azd/pkg/account/subscriptions_manager.go
  cli/azd/pkg/auth/credential_providers.go
  cli/azd/pkg/auth/manager.go
  cli/azd/pkg/auth/manager_test.go
  cli/azd/pkg/auth/public.go
  cli/azd/pkg/azureutil/location.go
  cli/azd/pkg/azureutil/principal.go
  cli/azd/pkg/commands/pipeline/pipeline_manager.go
  cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
  cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
  cli/azd/pkg/infra/provisioning/bicep/prompt.go
  cli/azd/pkg/infra/provisioning/bicep/prompt_test.go
  cli/azd/pkg/infra/provisioning/manager.go
  cli/azd/pkg/infra/provisioning/manager_test.go
  cli/azd/pkg/infra/provisioning/provider.go
  cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
  cli/azd/pkg/infra/provisioning/test/test_provider.go
  cli/azd/pkg/input/console.go
  cli/azd/pkg/project/framework_service_docker_test.go
  cli/azd/pkg/project/project.go
  cli/azd/pkg/project/project_config.go
  cli/azd/pkg/project/project_config_test.go
  cli/azd/pkg/project/project_test.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_target_containerapp.go
  cli/azd/pkg/project/service_target_containerapp_test.go
  cli/azd/pkg/project/service_test.go
  cli/azd/pkg/tools/azcli/account.go
  cli/azd/pkg/tools/azcli/ad.go
  cli/azd/pkg/tools/azcli/ad_test.go
  cli/azd/pkg/tools/azcli/azcli.go
  cli/azd/pkg/tools/azcli/subscriptions.go
  cli/azd/pkg/tools/azcli/user_profile.go
  cli/azd/pkg/tools/azcli/user_profile_test.go
  cli/azd/test/mocks/mock_credentials.go
  cli/azd/test/mocks/mockaccount/mock_manager.go
  cli/azd/test/mocks/mockinput/mock_console.go
  go.mod
  go.sum
Labels: blocker

#1452 Allow `init` to initialize git repository, restore executable file permissions
  cli/azd/.vscode/cspell-azd-dictionary.txt
  cli/azd/cmd/init.go
  cli/azd/internal/repository/initializer.go
  cli/azd/internal/repository/initializer_test.go
  cli/azd/internal/repository/testdata/template/script/test.sh.txt
  cli/azd/internal/telemetry/storage_test.go
  cli/azd/pkg/output/ux/done.go
  cli/azd/pkg/tools/git/git.go
  cli/azd/test/functional/cli_test.go
Labels: blocker

#1497 Azure App Service - Enhancement to specify health check endpoint
  templates/common/infra/bicep/core/host/appservice.bicep
  templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode.tf
  templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode_variables.tf
  templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython.tf
  templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython_variables.tf
Labels: customer-reported

#1535 Update `CODEOWNERS` paths: fix invalid paths
  .github/CODEOWNERS
Labels: engsys

#1581 Templates: Adds open in codespaces badge & links
  templates/todo/projects/csharp-cosmos-sql/README.md
  templates/todo/projects/csharp-sql-swa-func/README.md
  templates/todo/projects/csharp-sql/README.md
  templates/todo/projects/java-mongo-aca/README.md
  templates/todo/projects/java-mongo/README.md
  templates/todo/projects/nodejs-mongo-aca/README.md
  templates/todo/projects/nodejs-mongo-swa-func/README.md
  templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
  templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
  templates/todo/projects/nodejs-mongo/README.md
  templates/todo/projects/python-mongo-aca/README.md
  templates/todo/projects/python-mongo-swa-func/README.md
  templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
  templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
  templates/todo/projects/python-mongo/README.md
Labels: templates
