Repository Azure/azure-dev, pull requests merged in 2024-03, with the labels that each got.

#3450 Adds support for external container registries
  cli/azd/pkg/project/container_helper.go
  cli/azd/pkg/project/container_helper_test.go
Labels: aks, aca

#3492 Fixes edge case issue of a false positive AKS deployment failure
  cli/azd/pkg/project/service_target_aks.go
Labels: aks

#3479 stop spinner during params prompt
  cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
  cli/azd/pkg/infra/provisioning/bicep/prompt.go
  cli/azd/pkg/input/console.go
Labels: blocker, aspire

#3506 Fixes service config handlers referencing stale components
  cli/azd/cmd/cobra_builder.go
  cli/azd/cmd/cobra_builder_test.go
  cli/azd/cmd/container.go
  cli/azd/cmd/env.go
  cli/azd/cmd/middleware/hooks.go
  cli/azd/pkg/infra/provisioning/manager.go
  cli/azd/pkg/project/service_config.go
  cli/azd/pkg/project/service_manager.go
Labels: blocker

#3513 update rules for setting secret env vars for projects
  cli/azd/pkg/apphost/generate.go
  cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
Labels: blocker
