Repository Azure/azure-dev, pull requests merged in 2024-05, with the labels that each got.

#3845 Split "from source" into separate question
  ext/vscode/src/commands/cmdUtil.ts
  ext/vscode/src/commands/init.ts
Labels: blocker

#3854 Updating service plan to B3.
  templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
  templates/todo/projects/csharp-sql/.repo/bicep/infra/main.bicep
  templates/todo/projects/java-mongo/.repo/bicep/infra/main.bicep
  templates/todo/projects/nodejs-mongo/.repo/bicep/infra/main.bicep
  templates/todo/projects/python-mongo/.repo/bicep/infra/main.bicep
Labels: blocker

#3736 Update Azure resource types to include Video Indexer
  cli/azd/pkg/infra/azure_resource_types.go
Labels: customer-reported

#3933 [aspire]add known param - container env name
  cli/azd/pkg/apphost/generate.go
  cli/azd/pkg/apphost/generate_test.go
  cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-resources.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-resources.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireDashboardGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireDashboardGeneration-resources.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireStorageGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireStorageGeneration-resources.bicep.snap
  cli/azd/pkg/apphost/testdata/aspire-bicep.json
  cli/azd/resources/apphost/templates/main.bicept
  cli/azd/resources/apphost/templates/resources.bicept
  cli/azd/test/functional/testdata/snaps/aspire-full/infra/main.bicep
  cli/azd/test/functional/testdata/snaps/aspire-full/infra/resources.bicep
Labels: aspire

#3944 Reenables devcenter init/up/down tests
  cli/azd/test/functional/cli_test.go
Labels: flaky test, ade

#3942 Fixes issue selected environment with different environment type
  cli/azd/pkg/devcenter/environment_store.go
  cli/azd/pkg/devcenter/environment_store_test.go
  cli/azd/pkg/devcenter/manager.go
  cli/azd/pkg/environment/data_store.go
  cli/azd/pkg/environment/local_file_data_store.go
  cli/azd/pkg/environment/local_file_data_store_test.go
  cli/azd/pkg/environment/manager.go
  cli/azd/pkg/environment/manager_test.go
  cli/azd/pkg/environment/storage_blob_data_store.go
  cli/azd/pkg/environment/storage_blob_data_store_test.go
  cli/azd/test/functional/initialize_test.go
  cli/azd/test/mocks/mockenv/mock_manager.go
Labels: ade
