Repository Azure/azure-dev, pull requests merged in 2024-01, with the labels that each got.

#3170 Display mysql flexible server during provison
  cli/azd/pkg/infra/azure_resource_types.go
Labels: customer-reported

#3251 Adds flexibility when resolving container registry names
  cli/azd/pkg/project/container_helper.go
  cli/azd/pkg/project/container_helper_test.go
  cli/azd/pkg/project/framework_service_docker.go
  cli/azd/pkg/project/service_target_dotnet_containerapp.go
  schemas/alpha/azure.yaml.json
Labels: aks, aca

#3249 Adds flexibility when resolving AKS cluster names
  cli/azd/pkg/project/service_target_aks.go
  cli/azd/pkg/project/service_target_aks_test.go
Labels: aks
