Repository Azure/azure-dev, pull requests merged in 2024-10, with the labels that each got.

#4371 [Aspire] Add support for default.value for parameter.v0
  cli/azd/pkg/apphost/generate.go
  cli/azd/pkg/apphost/manifest.go
  cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-main.bicep.snap
  cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-main.parameters.json.snap
  cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-mysqlabstract.snap
  cli/azd/pkg/apphost/testdata/aspire-container.json
  cli/azd/pkg/project/service_target_dotnet_containerapp.go
  cli/azd/resources/apphost/templates/main.bicept
Labels: blocker, aspire

#4416 Remove experimentation middleware from global middleware list
  cli/azd/cmd/root.go
  cli/azd/test/functional/experiment_test.go
Labels: blocker

#4450 fix persistSettings regression
  cli/azd/CHANGELOG.md
  cli/azd/pkg/containerapps/container_app.go
  cli/version.txt
Labels: blocker

#4039 Use DOTNET_CONTAINER_*
  cli/azd/pkg/tools/dotnet/dotnet.go
Labels: customer-reported
